import random
import operator

f = open('funnies.txt', 'r+')
f.truncate(0) # need '0' when using r+
f.close()

array = ([
"what the goofy goober",
"have you ever had a dream where you when you you and you when and you have and did you could",
"and then he blew up 🥀",
"mods, burger this man",
"jarvis, blow him up",
"can you burger a burger if it already has burgered its burger?",
"IT'S ALWAYS IN DEVELOPMENT",
"NEVER FINISHED",
"♫ do you want to build a mindaman? ♫",
"sponglesporb and partrickith",
"hit it with a stanky leg",
"Day 6969 of your daily warning to report and Mindaraffes that you see",
"what the helliante",
"wat is a mindaraffe and why is it asking for my SSN",
":D",
"cerealposting",
"+10000000 clout",
"-1 bajillion chinese social credit",
"all hail the little critter",
"⚠️ TRADE OFFER ⚠️",
"we do a little trolling",
'what does "based" mean?',
"DO NOT REDEEM 😡",
"committing multiple war crimes since 2000",
"waltuh",
"waltuh, don't do it waltuh",
"that's mad freaky waltuh",
"professional introvert talking",
"hello there young lady, OHHHHHH",
"dummby",
"bazinga",
"BAZINGA",
"BAZINGAPOSTING",
"GUYS HELP I CANNOT STOP bazinga",
"obamna, *applause*",
"minda, i am your father",
"mindafreaky",
"guys am i cool?",
"GET FREE VIEWERS AT MY DEFINITELY NOT SUSPICIOUS LINK!! [[Hyperlink Blocked]]",
"oh my goodness an amogus reference",
"deltarune metioned: 🤩🤩🤩🤩🤩",
"you have been served... burger 🍔",
"but, when did i ask?",
"your honor, might i remind you, my client is having a birthday party later. did i also mention that spiderman will be there?",
"you dont want to see my dark side",
"sip on it scout",
"cityboyyyy",
"i promise i will kill you",
"top ten: 10",
"GET OUT 🗣🗣🗣",
"who's coming?",
"huh?",
"if you're coming right now let me see it",
"let me see it",
"huh. he. he who is coming.",
"POP QUIZ: marketplier, partkermlier, or markerplier",
"man im unalived",
"guh",
"official guh moment",
"FAMILY SIZED. 75% more mindaman",
"what is a scroogilion",
"hello everybody my name is welcome",
"you're so portuguesed",
"running out of ideas and running from the police 🚓 🚓",
"gambling",
"I CANT STOP WINNING",
"AW DANG IT",
"LETS GO GAMBLING",
"lets go golfing!",
"we are so back",
"nvm we are no longer back",
'"no pain, no gain" -someone who pained and did not gain',
"dawg why is my lawyer 4 years old im cooked",
"imma arrested my lawyer because i just got call",
"the bonds name, james name",
"call a bondulance",
"two words donkey... SHUT. UP.",
"gringo",
"gringolicious",
"what if we renamed the little critter to gringo",
"midna is not minda, we are killing minda. WAIT NO-",
"getting sued by Nintendo since 2018",
"my lawyer wants to kill me",
"guys NO MORE SAYING CUSS WORDS",
"waht",
"wat",
"women :coffee cup emoji:",
"women ☕",
"java edition is better than no edition",
"bugrock moment",
"pattern recognition at its finest",
"500 cigarettes",
"2000 cigarettes",
"It is called, a cigarette",
"i was curious to taste it!",
"mods, crush his balls",
"alt + f4 = 1 scroogilion doolar",
"hello there",
"ice ice baby yoda drip",
"stream is ending: too cringe",
"session terminated",
"i hate this guy. unfollowed and hired an assassin",
"how dare you lose MY temper FOR ME",
"IM SO ANGRY",
"I hate being bipolar, it's so amazing!",
"i fo one",
"i font",
"like or subscribe. DO NOT DO BOTH YOU WILL DIE",
"scrubscrib",
"scrobbing and scribing",
"like and subscribe the video",
"this is bogus, my daddy is very rich",
"my mistake original gangster",
"now empty the compartments of your pantaloons",
"for what purpose?",
"hamburger cheeseburger, big mac, whopper",
"[insert video of spinning chip for 10 hours]",
"mods, quote that.",
"guys i couldnt get a job because of a quote on the mindamanreal channel. you ruined my life",
"snap back to reality",
"thanos will not snap back to reality",
"why would you whip, then nae nae. its completely disrespectful!",
"how dare you suggest that.",
"@supergayusername says super gay thing. nobody was suprised",
"jaw, dropped",
"baby, dropped kicked",
"as you see mr bond, you have become a brick",
"brick 🧱",
"🧱 incoming!",
"deep or shallow?",
"i prefer to be deep",
"i prefer to be shallow",
"my father likes to beat me, SUPERMAN",
"im not superman anymore im spiderman now",
"radioactive spider man",
"spiderman is the average american man but spidered",
"batman is 50% bat and 50% man, hence why hes so good at baseball",
"cry about it 😂🫵",
"basketballing",
"your honor, LUIGI IS BALLING",
"mods, do NOT impregnate that man",
"mods, add one electron to every atom in his body",
"this does not mama the mia",
"an IQ too high?",
"an IQ too low?",
"your honor my client is stupid",
"if i was lying, why aren’t my pants on fire? case closed",
"at this point, its not procrastinating, im just not doing it.",
"uh nuh",
"by the way im bisexual, hwo do i turn this shit off",
"WOAH! he's bisexual i had no idea!",
"some idiot left a 40 foot tall pineapple lying around",
"let me break it down for you...💃🕺💃🕺",
'"ts was NOT me bro" -the wind',
"yo that was the wind",
"bua bua bua! bua bua? bua. buabua bua bua bua BUA",
"unfunny joke incoming",
"what a GOOF NUGGET",
"and then, he clicked POST",
"please UNDERSTAND THE REFERENCE",
"chat, die.",
"ragebaiters should die",
'"address me" -elephant',
"when gambling, you can win 2000% of your money, but you can only lose 100%. Do the math",
"never stop the cope",
"HES PULLING HIS COCK OUT",
"why is my ai girlfriend calling me a prompstitute?",
"if gravity can pull an apple, you can pull a bad bih. Stay up gang",
"free gems in clash royal",
"hold up, the big leagues are calling me",
"19 dolar fortnate cord",
"left me my wife has",
"the owner of this stream was found alive :bigsad:",
"guys. do NOT post maxwell. I WILL BE VERY ANGRY😡😡😡",
"maxwell the cat",
"dingusposting",
"maxwell (dingus)",
"is multiple maxwell called a dingi or a maxwellious",
"misinfortnitemation",
"freakinator",
"his greed sickens me",
"you must be in compliance with mother china",
"all hail the CCP",
"james doakes should not have been that suspicious",
"james doakes was not the imposter",
"dexter morgan was the imposter",
"neuron activation",
"hey google, show me a picture of a furry",
"i will show you my dih",
"mindakisser moment",
"female enjoyer",
"did you know, loving a woman is GAY",
"when you're in china, chinese food is just food.",
"bean chilli",
"would you rather have 1$ or 2$",
"mr electric, KILL HIM",
"consume the brick",
"these censors are going to fucking kill me",
"turbo wank",
"KYS = keep yourself safe",
"good gracious look at those bozangas",
"your did it",
"blows up pancakes with mind",
"my fucking pancakes!",
'"see when viewers peaked, let me know when i peaked fr" -wizard',
"pride month is over, STOP BEING GAY",
"my spidey senses are tingling",
">be me >fish ><>",
"yarrr me cylinder is stuc in the barrel of me m&m's tube",
"i appear to have burst into flames",
"gregregation",
"guys, HTML is a STD.",
"i want to dead",
"you should preemptively enter your casket, THIS INSTANT 🎩🍵",
"lincolns last words -> this shows gonna be fire fr",
"can i get a pleaseburger cheese",
"can i get 2 mcflurries and a bigmac = can i get 2 furries playing with my ballsack",
"sesbian lex",
"say gex",
"the wizard is out of spells but never shells",
"aw shit, here we go again",
"i've come to make an announcement",
"he he he, yup",
"SIR GET DOWN, GET DOWN, SIR GET DOWN. hey! hey! hey! to the window! to the wall! to the wall!",
"man im dead",
"tomato",
'"im not picky", the unsuspecting 700th page',
"you wanna know how i got these scars? sharp. hamburger.",
"but daddy! i love him! GIVE ME THE FUCKING FORMULA KRABS",
"⚠️⚠️⚠️ BBQ CHICKEN ALERT ⚠️⚠️⚠️",
"not every dude with a beard- hi this is gabe."
    ])
random.shuffle(array)
arrayFull = '       •       '.join(array)

output = arrayFull[:3000]

for i in output:
  if not output.endswith("•"):
    output = output[:-1]
  else:
    break

output = str(output) + "       "

f = open('funnies.txt', 'w', encoding="utf-8")
f.write(output)
f.close()

